import { Exercise } from './types';

export const exercises: Exercise[] = [
  // NECK
  {
    id: 1,
    name: "Neck Stretch",
    bodyPart: "neck",
    difficulty: "beginner",
    equipment: "none",
    duration: "30s",
    reps: "Hold 30s",
    sets: 3,
    image: "/images/neck.png",
    instructions: [
      "Sit or stand with your back straight",
      "Slowly tilt your head to the right",
      "Hold for 30 seconds",
      "Return to center and repeat on the left side",
    ],
    benefits: ["Relieves neck tension", "Improves flexibility", "Reduces headaches"],
    safety: "Move slowly and stop if you feel sharp pain. Do not force the stretch.",
  },
  {
    id: 2,
    name: "Neck Rotation",
    bodyPart: "neck",
    difficulty: "beginner",
    equipment: "none",
    duration: "30s",
    reps: "10 each side",
    sets: 2,
    image: "/images/neck.png",
    instructions: [
      "Sit or stand tall with shoulders relaxed",
      "Slowly turn your head to the right as far as comfortable",
      "Hold 2–3 seconds, return to center",
      "Repeat on the left side",
    ],
    benefits: ["Improves neck mobility", "Reduces stiffness", "Enhances posture"],
    safety: "Avoid jerky movements; do not rotate beyond comfortable range.",
  },

  // SHOULDERS
  {
    id: 3,
    name: "Shoulder Rolls",
    bodyPart: "shoulder",
    difficulty: "beginner",
    equipment: "none",
    duration: "45s",
    reps: "10-15",
    sets: 2,
    image: "/images/shoulder.png",
    instructions: [
      "Stand with feet shoulder-width apart",
      "Roll shoulders forward in a circular motion 10–15 times",
      "Then roll backward 10–15 times",
    ],
    benefits: ["Improves shoulder mobility", "Reduces stiffness", "Increases blood flow"],
    safety: "Keep movements controlled, avoid jerking shoulders.",
  },
  {
    id: 4,
    name: "Wall Push-ups",
    bodyPart: "shoulder",
    difficulty: "beginner",
    equipment: "none",
    duration: "45s",
    reps: "8-12",
    sets: 3,
    image: "/images/wall-pushup.png",
    instructions: [
      "Stand at arm’s length from wall",
      "Place palms flat on the wall at shoulder height",
      "Lean forward and push back slowly",
    ],
    benefits: ["Strengthens shoulders and arms", "Improves upper-body stability"],
    safety: "Keep movements controlled. Stop if shoulder/wrist pain occurs.",
  },

  // BACK
  {
    id: 5,
    name: "Cat–Cow Stretch",
    bodyPart: "back",
    difficulty: "beginner",
    equipment: "mat",
    duration: "60s",
    reps: "8-10",
    sets: 2,
    image: "/images/cat-cow-stretch.png",
    instructions: [
      "Start on hands and knees",
      "Inhale: arch back, look up (cow)",
      "Exhale: round back, tuck chin (cat)",
      "Repeat smoothly",
    ],
    benefits: ["Improves spinal flexibility", "Reduces back stiffness", "Enhances posture"],
    safety: "Move slowly; avoid forcing spine. Stop if pain occurs.",
  },
  {
    id: 6,
    name: "Seated Spinal Twist",
    bodyPart: "back",
    difficulty: "intermediate",
    equipment: "chair",
    duration: "45s",
    reps: "Hold 20s each side",
    sets: 2,
    image: "/images/seated-spinal-twist.png",
    instructions: [
      "Sit on a chair with back straight",
      "Twist torso gently to the right, hold 20s",
      "Repeat on left side",
    ],
    benefits: ["Improves spinal mobility", "Reduces stiffness", "Enhances digestion"],
    safety: "Do not force twist; avoid if you have recent spine injuries.",
  },

  // CORE
  {
    id: 7,
    name: "Plank",
    bodyPart: "core",
    difficulty: "intermediate",
    equipment: "mat",
    duration: "30s",
    reps: "Hold 30s",
    sets: 3,
    image: "/images/plank-exercise.png",
    instructions: [
      "Start on elbows and toes, body straight",
      "Engage core and glutes",
      "Hold position",
    ],
    benefits: ["Strengthens core", "Improves posture", "Enhances stability"],
    safety: "Avoid sagging hips; modify if lower back pain occurs.",
  },
  {
    id: 8,
    name: "Dead Bug",
    bodyPart: "core",
    difficulty: "intermediate",
    equipment: "mat",
    duration: "60s",
    reps: "8-10 each side",
    sets: 2,
    image: "/images/dead-bug.png",
    instructions: [
      "Lie on back, arms up, knees bent 90°",
      "Extend right arm and left leg slowly",
      "Return to start, switch sides",
    ],
    benefits: ["Strengthens core stability", "Improves coordination"],
    safety: "Move slowly, maintain lower back contact with mat.",
  },

  // HIPS
  {
    id: 9,
    name: "Hip Flexor Stretch",
    bodyPart: "hip",
    difficulty: "intermediate",
    equipment: "mat",
    duration: "60s",
    reps: "Hold 30s each side",
    sets: 2,
    image: "/images/hip.png",
    instructions: [
      "Kneel on one knee, other foot forward",
      "Push hips gently forward, hold 30s",
      "Switch sides",
    ],
    benefits: ["Improves hip flexibility", "Reduces tightness", "Supports lower back"],
    safety: "Keep back straight; avoid forcing stretch.",
  },
  {
    id: 10,
    name: "Glute Bridge",
    bodyPart: "hip",
    difficulty: "beginner",
    equipment: "mat",
    duration: "45s",
    reps: "10-12",
    sets: 3,
    image: "/images/glute-bridge.png",
    instructions: [
      "Lie on back, knees bent, feet flat",
      "Lift hips until body forms straight line from shoulders to knees",
      "Hold 2s, lower slowly",
    ],
    benefits: ["Strengthens glutes and hamstrings", "Improves hip stability"],
    safety: "Avoid arching lower back excessively.",
  },

  // LEGS
  {
    id: 11,
    name: "Standing Quad Stretch",
    bodyPart: "leg",
    difficulty: "beginner",
    equipment: "none",
    duration: "30s",
    reps: "Hold 30s each leg",
    sets: 2,
    image: "/images/standing-quad-stretch.png",
    instructions: [
      "Stand tall and balance on one leg",
      "Grab ankle of opposite leg and pull heel toward glutes",
      "Hold 30s, switch legs",
    ],
    benefits: ["Stretches quadriceps", "Improves balance", "Reduces knee strain"],
    safety: "Hold onto a wall for balance if needed.",
  },
  {
    id: 12,
    name: "Calf Raises",
    bodyPart: "leg",
    difficulty: "beginner",
    equipment: "none",
    duration: "45s",
    reps: "12-15",
    sets: 3,
    image: "/images/calf-raises.png",
    instructions: [
      "Stand with feet hip-width apart",
      "Rise onto toes, hold 1-2s, lower slowly",
      "Repeat for desired reps",
    ],
    benefits: ["Strengthens calves", "Improves ankle stability", "Enhances circulation"],
    safety: "Keep movements slow to avoid ankle strain.",
  },
  {
    id: 13,
    name: "Lunges",
    bodyPart: "leg",
    difficulty: "intermediate",
    equipment: "none",
    duration: "60s",
    reps: "8-10 each leg",
    sets: 3,
    image: "/images/lunges.png",
    instructions: [
      "Step forward with one leg",
      "Lower hips until both knees are at 90°",
      "Push back to start, switch legs",
    ],
    benefits: ["Strengthens quads, glutes, and hamstrings", "Improves balance"],
    safety: "Avoid letting knee go past toes; maintain upright posture.",
  },
  {
    id: 14,
    name: "Side-Lying Leg Lift",
    bodyPart: "leg",
    difficulty: "beginner",
    equipment: "mat",
    duration: "45s",
    reps: "10-12 each leg",
    sets: 2,
    image: "/images/side-lying-leg-lift.png",
    instructions: [
      "Lie on side, legs straight",
      "Lift top leg to 45°, lower slowly",
      "Repeat for desired reps, switch sides",
    ],
    benefits: ["Strengthens hip abductors", "Improves hip stability"],
    safety: "Avoid rotating hips; keep body aligned.",
  },

  // ARMS
  {
    id: 15,
    name: "Bicep Curl with Water Bottle",
    bodyPart: "arm",
    difficulty: "beginner",
    equipment: "water bottle",
    duration: "45s",
    reps: "10-12",
    sets: 3,
    image: "/images/bicep-curl.png",
    instructions: [
      "Hold bottle in one hand, arm at side",
      "Curl toward shoulder, lower slowly",
      "Switch arms",
    ],
    benefits: ["Strengthens biceps", "Improves arm tone"],
    safety: "Avoid swinging; keep elbow close to torso.",
  },
  {
    id: 16,
    name: "Tricep Dips on Chair",
    bodyPart: "arm",
    difficulty: "intermediate",
    equipment: "chair",
    duration: "45s",
    reps: "10-12",
    sets: 3,
    image: "/images/tricep-dips.png",
    instructions: [
      "Sit on edge of chair, hands gripping edge",
      "Slide forward, lower body, push back up",
    ],
    benefits: ["Strengthens triceps", "Improves arm stability"],
    safety: "Keep shoulders away from ears; avoid locking elbows.",
  },

  // FULL BODY
  {
    id: 17,
    name: "Mountain Climbers",
    bodyPart: "full body",
    difficulty: "intermediate",
    equipment: "mat",
    duration: "30s",
    reps: "20-30",
    sets: 3,
    image: "/images/mountain-climbers.png",
    instructions: [
      "Start in plank position",
      "Drive knees alternately toward chest quickly",
    ],
    benefits: ["Improves cardiovascular fitness", "Strengthens core and legs"],
    safety: "Maintain plank form; avoid sagging hips.",
  },
  {
    id: 18,
    name: "Jumping Jacks",
    bodyPart: "full body",
    difficulty: "beginner",
    equipment: "none",
    duration: "30s",
    reps: "20-30",
    sets: 3,
    image: "/images/jumping-jacks.png",
    instructions: [
      "Stand tall, jump feet out while raising arms overhead",
      "Jump back to start position",
    ],
    benefits: ["Improves cardiovascular fitness", "Enhances coordination"],
    safety: "Land softly to reduce joint impact.",
  },
  {
    id: 19,
    name: "Burpees (Modified)",
    bodyPart: "full body",
    difficulty: "advanced",
    equipment: "none",
    duration: "45s",
    reps: "8-10",
    sets: 2,
    image: "/images/burpees.png",
    instructions: [
      "Start standing, squat and place hands on floor",
      "Step back into plank, return to squat, stand up",
    ],
    benefits: ["Full-body conditioning", "Improves endurance"],
    safety: "Move at controlled pace; modify by skipping jump if needed.",
  },

  // STRETCHES / MOBILITY
  {
    id: 20,
    name: "Child’s Pose",
    bodyPart: "back",
    difficulty: "beginner",
    equipment: "mat",
    duration: "60s",
    reps: "Hold 60s",
    sets: 1,
    image: "/images/childs-pose.png",
    instructions: [
      "Kneel on mat, sit back on heels",
      "Reach arms forward, lower forehead to mat",
    ],
    benefits: ["Stretches spine, hips, and shoulders", "Reduces tension"],
    safety: "Avoid if knee injury; use cushion under knees if needed.",
  },
  {
    id: 21,
    name: "Cobra Stretch",
    bodyPart: "back",
    difficulty: "beginner",
    equipment: "mat",
    duration: "30s",
    reps: "Hold 30s",
    sets: 2,
    image: "/images/cobra-stretch.jpg",
    instructions: [
      "Lie face down, hands under shoulders",
      "Push chest up, keep hips on floor",
      "Hold, then return",
    ],
    benefits: ["Opens chest", "Stretches spine", "Improves posture"],
    safety: "Do not overarch; stop if back pain occurs.",
  },
  {
    id: 22,
    name: "Seated Hamstring Stretch",
    bodyPart: "leg",
    difficulty: "beginner",
    equipment: "mat",
    duration: "30s",
    reps: "Hold 30s each leg",
    sets: 2,
    image: "/images/seated-hamstring-stretch.png",
    instructions: [
      "Sit on floor, legs straight",
      "Reach toward toes, keep back straight",
      "Hold stretch, switch legs",
    ],
    benefits: ["Improves hamstring flexibility", "Reduces lower back tension"],
    safety: "Do not bounce; reach only as comfortable.",
  },
  {
    id: 23,
    name: "Hip Circles",
    bodyPart: "hip",
    difficulty: "beginner",
    equipment: "none",
    duration: "45s",
    reps: "10 each direction",
    sets: 2,
    image: "/images/hip.png",
    instructions: [
      "Stand with hands on hips",
      "Rotate hips in a circular motion clockwise, then counterclockwise",
    ],
    benefits: ["Improves hip mobility", "Warms up lower body"],
    safety: "Keep knees soft; move smoothly.",
  },
  {
    id: 24,
    name: "Ankle Circles",
    bodyPart: "leg",
    difficulty: "beginner",
    equipment: "none",
    duration: "30s",
    reps: "10 each ankle",
    sets: 2,
    image: "/images/ankle.png",
    instructions: [
      "Sit or stand, lift one foot off floor",
      "Rotate ankle clockwise and counterclockwise",
      "Switch ankles",
    ],
    benefits: ["Improves ankle mobility", "Reduces stiffness"],
    safety: "Move slowly; avoid pain.",
  },
  {
    id: 25,
    name: "Standing Side Bend",
    bodyPart: "core",
    difficulty: "beginner",
    equipment: "none",
    duration: "30s",
    reps: "8-10 each side",
    sets: 2,
    image: "/images/standing-side-bend.png",
    instructions: [
      "Stand feet shoulder-width apart",
      "Reach one arm overhead, bend sideways",
      "Return to center, switch sides",
    ],
    benefits: ["Stretches obliques", "Improves lateral flexibility"],
    safety: "Do not twist spine; keep movements controlled.",
  },
];
